# 1. Forzar al microservicio a usar su puerto correcto
server.port=8081

# 2. Credenciales para conectarse al XAMPP (MySQL) de esta nueva PC
spring.datasource.url=jdbc:mysql://localhost:3306/ecogarzones_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de Hibernate para interactuar con las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. El nombre de tu aplicación (el que ya tenías)
spring.application.name=ecogarzones